import 'package:get/get.dart';
import 'package:meetmern/view/controllers/authcontroller/ForgetPasswordScreens/forget_password_screen_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/ForgetPasswordScreens/setnew_password_screen_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/loginScreen/login_screen_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/OTPScreens/otp_verify_screen_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/OTPScreens/verify_otp_controller_widget_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/SignupScreen/signup_screen_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/SplashScreens/splash_screen_1_controller.dart';
import 'package:meetmern/view/controllers/authcontroller/SplashScreens/splash_screen_2_controller.dart';
import 'package:meetmern/view/controllers/chat_controller/chat_detail_screen_controller.dart';
import 'package:meetmern/view/controllers/chat_controller/chat_screen_controller.dart';
import 'package:meetmern/view/controllers/chat_controller/message_screen_controller.dart';
import 'package:meetmern/view/controllers/chat_controller/user_meetup_info_screen_controller.dart';
import 'package:meetmern/view/controllers/home_controller/CreateMeetupScreen/create_meetup_controller.dart';
import 'package:meetmern/view/controllers/home_controller/CreateMeetupScreen/review_meetup_controller.dart';
import 'package:meetmern/view/controllers/home_controller/ExploreScreen/explore_meetups_screen_controller.dart';
import 'package:meetmern/view/controllers/home_controller/FilterScreen/filter_screen_controller.dart';
import 'package:meetmern/view/controllers/home_controller/MeetupUserProfileScreen/meetup_user_profile_screen_controller.dart';
import 'package:meetmern/view/controllers/home_controller/RequestMeetupScreen/request_meetup_screen_controller.dart';
import 'package:meetmern/view/controllers/home_controller/ViewMeetupScreen/repeat_meetup_dialog_controller.dart';
import 'package:meetmern/view/controllers/home_controller/ViewMeetupScreen/view_meetup_screen_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/OnboardingScreen/onboarding_screen_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/about_page_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/basics_page_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/final_page_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/interests_page_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/location_page_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/onboarding_topbar_controller.dart';
import 'package:meetmern/view/controllers/onboarding_controller/pages/photo_page_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/AccountPrefrences/account_prefrences_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/BlockedUser/block_user_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/Favourites/favourites_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/Feedback&Support/feedback&support_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/LocationScreen/location_screen_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ManageAds/ads_screen_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ManageAds/delete_meetup_screen_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/NotificationScreens/notification_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ProfileMenuItemsScreens/personal_profile_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ProfileMenuItemsScreens/personal_profile_setting_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ProfileMenuItemsScreens/setting_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ViewProfileScreens/profile_details_controller.dart';
import 'package:meetmern/view/controllers/userprofile_controller/ViewProfileScreens/view_profil_controller.dart';

class AppBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<SplashController>(() => SplashController(), fenix: true);
    Get.lazyPut<Splash2Controller>(() => Splash2Controller(), fenix: true);
    Get.lazyPut<LoginController>(() => LoginController(), fenix: true);
    Get.lazyPut<SignupController>(() => SignupController(), fenix: true);
    Get.lazyPut<ForgotPasswordController>(() => ForgotPasswordController(), fenix: true);
    Get.lazyPut<ResetPasswordController>(() => ResetPasswordController(), fenix: true);
    Get.lazyPut<OtpWidgetController>(() => OtpWidgetController(), fenix: true);
    Get.lazyPut<OtpVerifyController>(() => OtpVerifyController(), fenix: true);
    Get.lazyPut<ChatListController>(() => ChatListController(), fenix: true);
    Get.lazyPut<ChatDetailController>(() => ChatDetailController(), fenix: true);
    Get.lazyPut<UserMeetupInfoController>(() => UserMeetupInfoController(), fenix: true);
    Get.lazyPut<CreateMeetupController>(() => CreateMeetupController(), fenix: true);
    Get.lazyPut<ReviewMeetupController>(() => ReviewMeetupController(), fenix: true);
    Get.lazyPut<ExploreController>(() => ExploreController(), fenix: true);
    Get.lazyPut<FilterController>(() => FilterController(), fenix: true);
    Get.lazyPut<MeetupUserProfileController>(() => MeetupUserProfileController(), fenix: true);
    Get.lazyPut<RequestMeetupController>(() => RequestMeetupController(), fenix: true);
    Get.lazyPut<RepeatMeetupDialogController>(() => RepeatMeetupDialogController(), fenix: true);
    Get.lazyPut<ViewMeetupController>(() => ViewMeetupController(), fenix: true);
    Get.lazyPut<OnboardingController>(() => OnboardingController(), fenix: true);
    Get.lazyPut<AboutPageController>(() => AboutPageController(), fenix: true);
    Get.lazyPut<BasicsPageController>(() => BasicsPageController(), fenix: true);
    Get.lazyPut<FinalPageController>(() => FinalPageController(), fenix: true);
    Get.lazyPut<InterestsPageController>(() => InterestsPageController(), fenix: true);
    Get.lazyPut<LocationPageController>(() => LocationPageController(), fenix: true);
    Get.lazyPut<OnboardingTopbarController>(() => OnboardingTopbarController(), fenix: true);
    Get.lazyPut<PhotoPageController>(() => PhotoPageController(), fenix: true);
    Get.lazyPut<AccountPreferencesController>(() => AccountPreferencesController(), fenix: true);
    Get.lazyPut<BlockedUserController>(() => BlockedUserController(), fenix: true);
    Get.lazyPut<FavouritesController>(() => FavouritesController(), fenix: true);
    Get.lazyPut<FeedbackSupportController>(() => FeedbackSupportController(), fenix: true);
    Get.lazyPut<LocationScreenController>(() => LocationScreenController(), fenix: true);
    Get.lazyPut<AdsScreenController>(() => AdsScreenController(), fenix: true);
    Get.lazyPut<DeleteMeetupController>(() => DeleteMeetupController(), fenix: true);
    Get.lazyPut<NotificationController>(() => NotificationController(), fenix: true);
    Get.lazyPut<PersonalProfileController>(() => PersonalProfileController(), fenix: true);
    Get.lazyPut<PersonalProfileSettingController>(() => PersonalProfileSettingController(), fenix: true);
    Get.lazyPut<SettingController>(() => SettingController(), fenix: true);
    Get.lazyPut<ProfileDetailsController>(() => ProfileDetailsController(), fenix: true);
    Get.lazyPut<ViewProfileController>(() => ViewProfileController(), fenix: true);
  }
}
