// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // DEBUG-ONLY: defaultValue keys inlined so the app runs without
  // --dart-define-from-file. TODO: revert to bare String.fromEnvironment.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('ANDROID_FIREBASE_API_KEY',
        defaultValue: 'AIzaSyCCw4zVop-Jx_qJ-amXKzzFBsr72YCs7F4'),
    appId: String.fromEnvironment('ANDROID_FIREBASE_APP_ID',
        defaultValue: '1:925940972492:android:001df3f4a357a9de8afb69'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '925940972492'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'meetmerightnow-299b6'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'meetmerightnow-299b6.firebasestorage.app'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_FIREBASE_API_KEY',
        defaultValue: 'AIzaSyB_vUoS1fIT8nj03UfpKOGG0mBm7pUlbGc'),
    appId: String.fromEnvironment('IOS_FIREBASE_APP_ID',
        defaultValue: '1:925940972492:ios:1dde74ca62e5a7078afb69'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '925940972492'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'meetmerightnow-299b6'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'meetmerightnow-299b6.firebasestorage.app'),
    iosClientId: String.fromEnvironment('IOS_FIREBASE_CLIENT_ID',
        defaultValue:
            '925940972492-57srnrhf5hqp3mfv2fe76v541b83vpdr.apps.googleusercontent.com'),
    iosBundleId: String.fromEnvironment('IOS_BUNDLE_ID',
        defaultValue: 'com.example.meetmern'),
  );
}
